### PR TITLE
OP_CAT

### PR DESCRIPTION
**Pull request by DanGould**
@0xBEEFCAF3

### CODE REVIEW

**Comment by stevenroose** [comment]
Is OP_CAT really a covenant proposal? :sweat_smile: It's more like a building block for several of them, no?

**Comment by 0xBEEFCAF3** [comment]
> Is OP_CAT really a covenant proposal? 😅 It's more like a building block for several of them, no?

Yeah, this is the point I try to get across to people.

**Comment by stevenroose** [comment]
Maybe we can have a page in the EXTRA section on OP_CAT. So that we can link to it from all the proposals?

**Comment by 0xBEEFCAF3** [comment]
> Maybe we can have a page in the EXTRA section on OP_CAT. So that we can link to it from all the proposals?

I like this idea 👍

**Comment by stevenroose** [comment]
Did that in 5a9c31b8c395499b6c8408a647e771bd03707fe3.

**Pull request closed without merging**
