### PR TITLE
Update spacechains row for ctv

### PR DESCRIPTION
**Pull request by 1440000bytes**

### CODE REVIEW

**Comment by moonsettler** [comment]
APO should be No for Ark and CTV should be Yes for Ark, CTV can do the ATLC and APO can't.

**Comment by stevenroose** [comment]
> APO should be No for Ark and CTV should be Yes for Ark, CTV can do the ATLC and APO can't.

APO and CTV are kinda symmetric as you can use APO with the signature in the output to emulate CTV and you can emulate APO by doing CTV and a sig check with CSFS.

@op, can you elaborate on how Spacechains with CTV would work? Pre-calculated BMM like with pre-signed?

**Comment by 1440000bytes** [comment]
> Spacechains are already possible without covenants, but yes, just about any covenant proposal that lets you pre-commit the next tx would be useful for spacechains.

https://delvingbitcoin.org/t/lnhance-bips-and-implementation/376/10

Simple CTV Spacechain: https://github.com/nbd-wtf/simple-ctv-spacechain/

I think we can add more information about trade-offs related to BMM below the summary table. However, writing "half" for CTV would be misleading.

**Comment by stevenroose** [comment]
ack

**Comment by stevenroose** [comment]
merged as b72065264e834ae948383a490f6506edaa76aebd

**Pull request closed without merging**
